spring.datasource.url=jdbc:postgresql://localhost:5432/matu_relaciones_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jackson.serialization.write-dates-as-timestamps=false

# Cambia el puerto para evitar conflicto con otro proceso usando 8080
server.port=8081
